# Generated by Django 3.2.23 on 2024-07-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courselesson_is_show_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.course', verbose_name='课程'),
            preserve_default=False,
        ),
    ]
